name:  Second Workflow
on: workflow_dispatch
jobs:
  multiaction:
    runs-on: ubuntu-latest
    steps:
      -name:  print_multiecho
       run:  |
            echo "First command"
            echo "Second Command"
          
      
